---
- name: Create variable precedence demo
  hosts: all
  debugger: on_failed
  tasks:
   - name: Debugger demo
     file:
      path: "{{file-path}}"
      state: touch 
   - name: Variable Precedence
     debug: 
       msg: inventory value is "{{var1}}"
   

