---
- name: Installing Orange HRM
  become: yes
  hosts: all
  tasks:
    - name: Download apache2
      apt:
        name: "{{apache2_software_download}}"
        update_cache: yes
        state: present
        autoclean: yes      
    - name: Install Software properties
      apt:
        name: "{{software_properties_download}}"
        state: present 
    - name: Add a repository for php
      apt_repository:
        repo: "{{add_apt_repository}}"
        update_cache: yes
        state: present  
    - name: Download the php dependent packages
      apt:
        name: "{{php_dependent_packages}}"
        state: present
    - name: Copy php ini file
      template:
        src: php.ini.j2
        dest: "{{php_ini_file}}"
       
    - name: Download the orange hrm file
      get_url:
        url: "{{orange_hrm_download_link}}"
        dest: "{{orange_hrm_download_path}}"
    - name: Create a directory orange hrm
      file: 
        path: "{{orange_hrm_path}}"
        state: directory
    - name: Unarchive the Orange HRM file
      unarchive:
        src: "{{orange_hrm_download_path}}"
        dest: "{{orange_hrm_path}}"
        remote_src: yes
    - name: Change Ownership of Orangehrm
      command: sudo chown -R www-data:www-data "{{orange_hrm_path}}"
    - name: Change mode of Orange hrm
      file:
        path: "{{orange_hrm_path}}"
        recurse: yes
        mode: '0755'
    - name: Copy orange hrm conf file 
      template:
        src: orangehrm.conf.j2
        dest: "{{orange_hrm_conf_path}}"
    - name: Change enable site
      command: sudo a2ensite orangehrm.conf
    - name: Change the permissions of the site
      command: sudo a2enmod rewrite
    - name: Enable apache2
      ansible.builtin.systemd:
        name: apache2.service
        enabled: yes
        state: restarted  
                
      
       
      
          
                       