---
- name: Installing Orange HRM
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
      upgrade: dist
      update_cache: yes
    - name: Install Software properties
      apt:
        name: "{{software_properties_download}}"
        state: present    