---
- name: Installing NOP ecommerce
  hosts: all
  become: yes
  tasks:
    - name: Getting the microsoft packages
      get_url: 
        url: "{{nopecommerce_download_url}}"
        dest: "{{nopecommerce_download_destination}}"
        
    - name: Install a .deb package
      apt:
        update_cache: yes
        deb: "{{nopecommerce_download_destination}}"
    - name: Install dotnet packages
      apt:
        name: "{{nopecommerce_dotnet_packages}}"
        state: present
    - name: Install Nginx
      apt:
        name: "{{nopecommerce_nginx_package}}"
        state: present    
              