---
- name: Installing NOP ecommerce
  hosts: all
  become: yes
  tasks:
    - name: Getting the microsoft packages
      get_url: 
        url: "{{nopecommerce_download_url}}"
        dest: "{{nopecommerce_download_destination}}"
        
    - name: Install a .deb package
      apt:
        update_cache: yes
        deb: "{{nopecommerce_download_destination}}"
    - name: Install dotnet packages
      apt:
        name: "{{nopecommerce_dotnet_packages}}"
        state: present
    - name: Install aspnet core package
      apt: name={{ item }}  state=latest
      loop: ['aspnetcore-runtime-3.1', 'unzip']    
    - name: Install Nginx
      apt:
        name: "{{nopecommerce_nginx_package}}"
        state: present 
    - name: sites available
      copy:
        src: default
        dest: "{{nginx_default_dest}}"
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{nginx_home_dir}}"
        state: directory
    - name: Download NOP Ecommerce
      get_url:
        url: "{{nopecommerce_download_file}}"
        dest: "{{nopecommerce_download_temp_location}}"    
    - name: Unarchive a file 
      unarchive:
        src: "{{nopecommerce_download_temp_location}}"
        dest: "{{nginx_home_dir}}"
        remote_src: yes
    - name: Create bin logs directories
      file: name={{ item }} state=directory
      loop: ['bin', 'logs']        
              